### PR TITLE
Applied custom changes

### PR DESCRIPTION
**Pull request by pgrimsehl**
[pg-0000] locale can be defined in project file and is used for
textformatting of value strings (e.g. decimal point)
[pg-0001] do not export empty records (use empty records to build folder
structures to organize records)
[pg-0002] decimals in doubleSpinBox increased from 3 to 4
[pg-0003] components can be selected in addition to fields when editing
records
[pg-0004] added description column to record field table and removed
tooltip
[pg-0005] added default icons for records, differentiating between empty
records and records with fields (simulate "folder hierarchy")

### CODE REVIEW

**Comment by npruehs** [comment]
@pgrimsehl 👍 great work there! I can see that you put great amount of work into this, and I really appreciate that! Just a few points here. Some might seem picky, but you know - collaborative development is all about coding standards :)

[pg-0000]
- [ ] Interesting point with the locale for decimal point! Does this actually work for you? For me, changing the locale of a project from en_US to de_DE didn't allow me to use commas as decimal symbols, but I seem to be running a lower Qt version than you do.
- [ ] If we're adding locale support, we need to add it to all spinboxes, e.g. also when specifying default values for field definitions.
- [ ] I don't think we need to work with QLocale* pointers in RecordsController. The examples from the official documentation suggest we can stick with QLocale objects and trust the copy contructors: http://doc.qt.io/qt-4.8/qlocale.html#details
- [ ] In RecordsController, please use `locale` as parameter name, and `this->locale = locale` as assignment for consistency with other setter methods.

[pg-0001]
- [ ] If we're not exporting empty records, we should avoid specifying them as `ParentId` when exporting their children.

[pg-0002]
Interesting ;)

[pg-0003]
Love it! Have been missing that for quite a while.

[pg-0004]
- [ ] Interesting to see that you added a description column to the record field table. This is major change to the UI layout, and I never felt like that's necessary, coming from Blizzard tools like the WarCraft III and StarCraft II editors. However, I'm not totally reluctant to add that - I'm just curious: Why did you come up with this?
- [ ] You can remove the tooltip code in RecordFieldsTableWidget then, instead of just commenting it out.

[pg-0005]
- [ ] I love the idea of folder icons. Actually, there is already #21 for this, so they might be generalized in the future - but we can keep them for now. Where did you get them from? I'm asking because we might need to add a license for them. You might also consider removing the gmTome_ prefix of the file names.
- [ ] We should consider the actual fields here (both the record fields and derived fields). Otherwise, child records might appear empty, while they're not.

emptychildrecord

[General]
- [ ] In Tools > Options > Build & Run > General, you can change the Default build directory from `../build-%{CurrentProject:Name}-%{CurrentKit:FileSystemName}-%{CurrentBuild:Name}` to `../Obj/build-%{CurrentProject:Name}-%{CurrentKit:FileSystemName}-%{CurrentBuild:Name}`. In any case, the folder build-Tome-Desktop_Qt_5_7_0_MSVC2015_64bit-Debug contains temporary output files and can safely be removed from the repository.

defaultbuilddirectory

- [ ] In TypesController.h, an additional include sneaked in that can be safely removed.
- [ ] You can remove all [pg-000x] comments now.

**Comment by pgrimsehl** [comment]
Hi there! I fixed several issues that sneaked in ;)

[pg-0000]
Setting the locale should work correctly now. Originally the reason to use a const QLocale* was to emphasize that the QLocale object was passed down from the project and is no mutable member of RecordsController.
With the latest commit I use a different approach to access the project locale from various places within the code. In Controller::setProject() the method QLocale::setDefault() is called and QLocale() instances with no parameters are passed to all Widgets that need locale specific formatting.
The user should be able to set the locale upon project creation or in a Project Settings dialog that can be accessed at any time while editing a project.

[pg-0001]

> If we're not exporting empty records, we should avoid specifying them as ParentId when exporting their children.

Not totally sure about that. At least it must be specified how empty parents in a hierarchy are handled. Image something like
`Record00 (non-empty)`
`|_Record01 (empty)`
`..|_Record02  (non-empty)`

Record01 will not be exported, so Record02 would have no ParentId at all, but actually is a grand-child of Record00.
In the current state this feature is broken, since empty children of non-emtpy parents wil not be exported, though they have inherited fields. This is something I need to fix.

[pg-0002]
Just a tweak. Perhaps this is a candidate for some kind of Project Settings dialog.

[pg-0003]
I imagine a third way to compose records by specifing Record Templates. This could be very convenient if a large amount of records of the same type must be created. Image a record "NPC" composed of 8 components (HealthComponent, InventoryComponent, FactionComponent, LocationComponent, etc.) that are shared with other record types. Each time a new NPC record should be created, all 8 components must be manually selected, which is error-prone and tedious. If we were able to set up such an NPC record once, save it as a template and than selecting that template for a new record, this would be a much better and safer workflow. This would also open the possibility to modify the template at a later point (for example by adding or removing a component) and propagate this change to all record based on that template, which would ease the maintainance of large data sets.

[pg-0004]
Just a preference. I'd like to see the description without waiting for tooltip to show up ;) Perhaps this could be a interface parameter in a Settings dialog.

[pg-0005]
Ancestor issue is fixed. The icons are taken from the Windows 10 Explorer.

[General]
Comment tags removed, as well as the build folders.

**Comment by npruehs** [comment]
Thanks, will take a look at it this evening!

[pg-0001]/[pg-0003]

Records do inherit all fields, along with their components and field values. Thus, concerning [pg-0001], by definition, children of empty records cannot be empty. Concerning [pg-0003], you can just create an NPC record and all eight components. All NPCs should derive from that record, and will automatically inherit all eight components along with their default values. Or am I missing something else here you're trying to achieve?

RecordsController



[pg-0003]
I imagine a third way to compose records by specifing Record Templates. This could be very convenient if a large amount of records of the same type must be created. Image a record "NPC" composed of 8 components (HealthComponent, InventoryComponent, FactionComponent, LocationComponent, etc.) that are shared with other record types. Each time a new NPC record should be created, all 8 components must be manually selected, which is error-prone and tedious. If we were able to set up such an NPC record once, save it as a template and than selecting that template for a new record, this would be a much better and safer workflow. This would also open the possibility to modify the template at a later point (for example by adding or removing a component) and propagate this change to all record based on that template, which would ease the maintainance of large data sets.

[pg-0004]
Just a preference. I'd like to see the description without waiting for tooltip to show up ;) Perhaps this could be a interface parameter in a Settings dialog.

[pg-0005]
Ancestor issue is fixed. The icons are taken from the Windows 10 Explorer.

[General]
Comment tags removed, as well as the build folders.
	@pgrimsehl 	changed: names of record icons

**Comment by npruehs** [comment]
Thanks, will take a look at it this evening! Are you familiar with Pull/Rebase in Git? Otherwise I will handle the merge conflicts on my side.

[pg-0001]/[pg-0003]

Records do inherit all fields, along with their components and field values. Thus, concerning [pg-0001], by definition, children of empty records cannot be empty. Concerning [pg-0003], you can just create an NPC record and all eight components. All NPCs should derive from that record, and will automatically inherit all eight components along with their default values. Or am I missing something else here you're trying to achieve?

`RecordsController::getInheritedFieldValues` will return a combined `RecordFieldValueMap` along the inheritance tree, for convenience.

https://github.com/npruehs/tome-editor/blob/develop/Source/Tome/Features/Records/Controller/recordscontroller.cpp

[pg-0000]/[pg-0002]/[pg-0004]

There is #16 for adding project settings. Whenever you come up with something you feel should be added, just add a comment there! Will add it in a upcoming release.

**Comment by pgrimsehl** [comment]
[pg-0001]/[pg-0003]
You're right, I was using Record::fieldValues during export when checking  for empty records. Now I'm using  RecordsController::getRecordFieldValues() to get inherited values too.
When applying this fix I noticed, that the table export is using the Record::fieldValues too, which I think is wrong for the same reason as above. I fixed this issue, could you check it? perhaps I misread the original code.

Defining a "NPCBase" record and adding empty children will definitely do the job. Though that NPCBase will get exported and must be ignored by the program that uses the data, since it is no actual NPC.

**Comment by npruehs** [comment]
Sure, will check later and merge back your pull request after. Looks very solid to me!

I see your point with NPCBase. Do you think it would help to have different kinds of exports, such as "export leafs only"? I'm considering adding something like "export roots only" for enabling the export of pure data structures (e.g. for generating ProtoBuf files).

**Comment by pgrimsehl** [comment]
Configuring the export behaviour would be great! And "export empty records" could be an option there too.
These option could either be configured in the Project settings or in a new export dialog.

**Comment by npruehs** [comment]
Alright, everything's been merged! Finally, I added the following commits:

* 851fca4642d59dea1ac8894051766bc381812e53 Boiled ignore list down a little.
* f9a98b6d6f14c9f6a6d851a5df022a7a0a9545d4 Switched to existing icons from Visual Studio Image Library, because we've already added their license.
* d305e405187e22591405d917923dc3d44e31527a When record icons need to be refreshed (e.g. because a field has been added), we're only refreshing that part of the record tree instead of the whole window now.
* 689210082eb678d6828c97d935287270d56fd594 Enabled opening old project files without Locale property.
* dab4cb4be79f8c8f4dbecc8289f612c6a374c8c5 Removed some obsolete fields and includes that sneaked in.
* fb05a462a4fcc22ae9b9b10ae19397083b111bcc Updated example project with Locale property.
* 0cae17e80b26a19fa7d02c13a56be00d5154d87c No longer exporting parent id if the parent is empty.
* a458f5233a56fc34e349057bf35c6b517867aea8 Correctly exporting all components and table values of inherited fields. Really, you'd been very observant there! Thanks for the hint.

For further configuring the export behaviour, I've added #62 

From our discussion, I learned that Project Settings definitely is something we should add soon. I've added that to the next milestone.

That concludes this pull request. Thanks for all the input!

**Pull request closed without merging**
