### PR TITLE
Usability changes

### PR DESCRIPTION
**Pull request by pgrimsehl**
[000] Command line export ( this feature still needs more error handling / error reporting )
[001] "Path" attribute for export templates, to reference export templates not located in the project directory
[002] After manually changing a record's id, the edit box is no longer linked to the display name edit box.
[003] "Extern" attribute for record sets and field definition sets. Can be used later to prevent the user from changing these definitions, but he will still be able to use them in his/her project.,

### CODE REVIEW

**Comment by npruehs** [comment]
1. Love the command-line support! There's already #49 for this - will review your implementation later.
1. The concept of "external" attributes is interesting as well. Figured you're gonna need this ;) I don't know exactly whether "external" is how I would call it, maybe "read-only" or something similar would be a better fit. Will take a look at it later!
1. Media/Icons/record_default.png and  Media/Icons/record_empty_default.png sneaked in again. Please remove them.
1. So have the changes in Source/Tome/Core/mainwindow.cpp and ource/Tome/Features/Records/Controller/recordscontroller.h. Please remove those changes as well. See https://github.com/npruehs/tome-editor/pull/64/files for details.

**Comment by pgrimsehl** [comment]
Sorry about that!
I'll definitely create a feature branch next time.

**Comment by npruehs** [comment]
No need to be sorry! The idea behind feature branches is just

* easier to review
* you get your individual changes merged back earlier

Thus, it's usually "better for everyone" ;)

**Comment by npruehs** [comment]
### [000] Command line export

df290ae80e4c36ccb79e4b44837ff5fd2d9e0cd9  and 95b7003785690e8a17792c13547d2804bda4723b moved command line support to dedicated classes. Arguments slightly changed, documentation will be added to the wiki with the next release. We can now open a project file via command line without starting an export.

Example arguments are:

```
-no-gui
-project "D:\Dev\SCM\tome-editor\Doc\Example\Tome Example Project.tproj"
-export JSON C:\Users\Nick\Desktop\Example
```

### [001] "Path" attribute for export templates, to reference export templates not located in the project directory

With 86545189c683aa70a6e24c9c012d056a2b9f6a9a  and 3886fdd14637176ec1fca70489f7910616bf56de we can now add/omit file extensions and/or use relative/absolute paths in arbitrary combinations.

### [002] After manually changing a record's id, the edit box is no longer linked to the display name edit box.

fc10e9a963698c99e4f9c9fa753d94324dc2265a fixed a bug that caused record ids to be locked forever.

### [003] "Extern" attribute for record sets and field definition sets. Can be used later to prevent the user from changing these definitions, but he will still be able to use them in his/her project. ###

I feel like "external" is a little too broad in its meaning - it is hard to explain what the implications of such a flag are. I think what we need here is to be able to mark data as read-only. Also, we should be able to mark data as read-only on record level, instead of file level.

I've removed the "extern" attribute for now, because it just added to code and file size without being used anywhere. We should discuss the exact implications of that flag, and add it back along with the corresponding feature implementation. I've opened #68 for this.

This concludes this pull request. Again, thanks for all the input!

**Pull request merged**
